services:
  - type: web
    name: vedarc-backend-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://vedarc:Vedarc6496@vedarc.venpk9a.mongodb.net/vedarc_internship?retryWrites=true&w=majority
      - key: JWT_SECRET_KEY
        value: vedarc-super-secret-jwt-key-2024-change-this
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USERNAME
        value: tech@vedarc.co.in
      - key: SMTP_PASSWORD
        sync: false
      - key: ADMIN_USERNAME
        value: admin@vedarc.co.in
      - key: ADMIN_PASSWORD
        value: vedarc-admin-2024-secure
      - key: HR_USERNAME
        value: hr@vedarc.co.in
      - key: HR_PASSWORD
        value: vedarc-hr-2024-secure
      - key: MANAGER_USERNAME
        value: manager@vedarc.co.in
      - key: MANAGER_PASSWORD
        value: vedarc-manager-2024-secure
      - key: FRONTEND_ORIGIN
        value: https://vedarc.co.in 